/* Generated by Yosys 0.69+165 (git sha1 7fa56b066-dirty, MinSizeRel, GNU /nix/store/z4c6k0mrlkwl3s4w9ysxc8vq1wylm3ms-gcc-wrapper-15.3.0/bin/g++ 15.3.0) */

(* hdlname = "bidir" *)
(* top =  1  *)
(* src = "bidir.v:1.1-22.10" *)
module bidir_uut(s, p, q);
  (* src = "bidir.v:1.26-1.27" *)
  input [4:0] s;
  wire [4:0] s;
  (* src = "bidir.v:1.41-1.42" *)
  inout [3:0] p;
  wire [3:0] p;
  (* src = "bidir.v:1.57-1.58" *)
  output [3:0] q;
  wire [3:0] q;
  wire p_IOBUF_IO_1_I;
  wire p_IOBUF_IO_1_O;
  wire p_IOBUF_IO_1_OEN;
  wire p_IOBUF_IO_2_O;
  wire p_IOBUF_IO_2_OEN;
  wire p_IOBUF_IO_I;
  (* force_downto = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:130.20-130.21" *)
  wire [0:0] p_IOBUF_IO_I_LUT4_F_I0;
  wire p_IOBUF_IO_O;
  wire p_IOBUF_IO_OEN;
  (* src = "bidir.v:9.6-9.7" *)
  wire r;
  wire r_IOBUF_O_I;
  (* force_downto = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] s_IBUF_I_1_O;
  (* force_downto = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:130.20-130.21" *)
  wire [3:0] s_IBUF_I_O;
  (* keep = 32'd1 *)
  IOBUF p_IOBUF_IO (
    .I(p_IOBUF_IO_I),
    .IO(p[3]),
    .O(p_IOBUF_IO_O),
    .OEN(p_IOBUF_IO_OEN)
  );
  (* keep = 32'd1 *)
  IOBUF p_IOBUF_IO_1 (
    .I(p_IOBUF_IO_1_I),
    .IO(p[1]),
    .O(p_IOBUF_IO_1_O),
    .OEN(p_IOBUF_IO_1_OEN)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h2)
  ) p_IOBUF_IO_1_I_LUT2_F (
    .F(p_IOBUF_IO_1_I),
    .I0(s_IBUF_I_O[1]),
    .I1(s_IBUF_I_1_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h1)
  ) p_IOBUF_IO_1_OEN_LUT2_F (
    .F(p_IOBUF_IO_1_OEN),
    .I0(p_IOBUF_IO_I_LUT4_F_I0),
    .I1(s_IBUF_I_1_O[1])
  );
  (* keep = 32'd1 *)
  IOBUF p_IOBUF_IO_2 (
    .I(s_IBUF_I_O[1]),
    .IO(p[0]),
    .O(p_IOBUF_IO_2_O),
    .OEN(p_IOBUF_IO_2_OEN)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) p_IOBUF_IO_2_OEN_LUT1_F (
    .F(p_IOBUF_IO_2_OEN),
    .I0(p_IOBUF_IO_I_LUT4_F_I0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'hcca0)
  ) p_IOBUF_IO_I_LUT4_F (
    .F(p_IOBUF_IO_I),
    .I0(p_IOBUF_IO_I_LUT4_F_I0),
    .I1(s_IBUF_I_O[1]),
    .I2(s_IBUF_I_O[2]),
    .I3(s_IBUF_I_O[3])
  );
  (* keep = 32'd1 *)
  IBUF p_IOBUF_IO_I_LUT4_F_I0_IBUF_O (
    .I(s[0]),
    .O(p_IOBUF_IO_I_LUT4_F_I0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h04)
  ) p_IOBUF_IO_OEN_LUT3_F (
    .F(p_IOBUF_IO_OEN),
    .I0(s_IBUF_I_1_O[1]),
    .I1(s_IBUF_I_O[2]),
    .I2(s_IBUF_I_O[3])
  );
  (* keep = 32'd1 *)
  OBUF q_OBUF_O (
    .I(p_IOBUF_IO_O),
    .O(q[3])
  );
  (* keep = 32'd1 *)
  OBUF q_OBUF_O_1 (
    .I(r),
    .O(q[2])
  );
  (* keep = 32'd1 *)
  OBUF q_OBUF_O_2 (
    .I(p_IOBUF_IO_1_O),
    .O(q[1])
  );
  (* keep = 32'd1 *)
  OBUF q_OBUF_O_3 (
    .I(p_IOBUF_IO_2_O),
    .O(q[0])
  );
  (* keep = 32'd1 *)
  IOBUF r_IOBUF_O (
    .I(r_IOBUF_O_I),
    .IO(p[2]),
    .O(r),
    .OEN(s_IBUF_I_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/yosys-review-build/share/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hae)
  ) r_IOBUF_O_I_LUT3_F (
    .F(r_IOBUF_O_I),
    .I0(s_IBUF_I_O[1]),
    .I1(s_IBUF_I_1_O[1]),
    .I2(s_IBUF_I_O[2])
  );
  (* keep = 32'd1 *)
  IBUF s_IBUF_I (
    .I(s[4]),
    .O(s_IBUF_I_O[3])
  );
  (* keep = 32'd1 *)
  IBUF s_IBUF_I_1 (
    .I(s[2]),
    .O(s_IBUF_I_1_O[1])
  );
  (* keep = 32'd1 *)
  IBUF s_IBUF_I_O_IBUF_O (
    .I(s[3]),
    .O(s_IBUF_I_O[2])
  );
  (* keep = 32'd1 *)
  IBUF s_IBUF_I_O_IBUF_O_1 (
    .I(s[1]),
    .O(s_IBUF_I_O[1])
  );
  assign { s_IBUF_I_1_O[2], s_IBUF_I_1_O[0] } = s_IBUF_I_O[2:1];
  assign s_IBUF_I_O[0] = p_IOBUF_IO_I_LUT4_F_I0;
endmodule
